# Generated by Django 5.2.12 on 2026-04-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_sourceaudio_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separatedtrack',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separated_tracks', to='preprocessing.sourceaudio'),
        ),
        migrations.AlterModelTable(
            name='separatedtrack',
            table='preprocessing_separated_track',
        ),
        migrations.AlterModelTable(
            name='sourceaudio',
            table='preprocessing_source_audio',
        ),
    ]
