# Generated by Django 5.2.12 on 2026-04-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0004_alter_separatedtrack_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceaudio',
            name='status',
        ),
    ]
