# Generated by Django 5.2.12 on 2026-03-27 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of the uploaded audio file', max_length=255)),
                ('file', models.FileField(upload_to='uploads/source_audio/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('PROCESSING', '변환중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
            ],
        ),
    ]
