# Generated by Django 5.2.12 on 2026-03-28 12:38

import django.db.models.deletion
import source_separator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_separator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparatedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('vocals', 'Vocals'), ('drums', 'Drums'), ('bass', 'Bass'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to=source_separator.models.track_directory_path)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separated_tracks', to='source_separator.sourceaudio')),
            ],
        ),
    ]
