# Generated by Django 5.2.12 on 2026-03-28 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_separator', '0002_separatedtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
