# Generated by Django 5.2.12 on 2026-05-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocessing', '0005_remove_sourceaudio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/source_audio/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_tracks', to='preprocessing.separatedtrack')),
            ],
        ),
    ]
