# Generated by Django 5.2.12 on 2026-05-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('preprocessing', '0005_remove_sourceaudio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effector_values', to='preprocessing.separatedtrack')),
            ],
        ),
    ]
