# Generated by Django 5.2.12 on 2026-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_effector'),
    ]

    operations = [
        migrations.AddField(
            model_name='effector',
            name='delay',
            field=models.CharField(blank=True, choices=[('off', 'Off'), ('50', '50%'), ('100', '100%')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='effector',
            name='distortion',
            field=models.CharField(blank=True, choices=[('off', 'Off'), ('50', '50%'), ('100', '100%')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='effector',
            name='phase',
            field=models.CharField(blank=True, choices=[('off', 'Off'), ('50', '50%'), ('100', '100%')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recordedtrack',
            name='file',
            field=models.FileField(upload_to='uploads/recorded_audio/%Y/%m/%d/'),
        ),
    ]
