# Generated by Django 5.2.12 on 2026-05-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_effector_delay_effector_distortion_effector_phase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effector',
            old_name='distortion',
            new_name='dist',
        ),
    ]
